### ISSUE TITLE
New default keybindings

### ISSUE THREAD

**Issue by raboof** [raboof/notion#114]
I think Notion 4 should come with a new set of keybindings.
* More consistent/memorable
* Navigate left-handed, query/rearrange(?) right-handed.
* Replace `META+K` with `ALTMETA`, and define `ALTMETA` as `META+Shift`.
* Keep it easy to switch back to the old keybindings

Probably:
* [x] Create a new `cfg_bindings.lua` with the new default bindings
* x Also put the (new) 'cfg_tiling.lua' bindings in `cfg_bindings.lua`.
* [x] Put old keybindings in `cfg_bindings_notion3.lua`
* [x] Make `cfg_notioncore.lua` empty aside from including `cfg_bindings.lua`
* [x] Put the new default bindings in `cfg_bindings.lua`
* [x] Add to the migration guide #113 that you can switch back by copying `cfg_bindings_notion3.lua` as `~/.notion/cfg_bindings.lua`
* [ ] Make sure `ALTMETA=""` is interpreted as `ALTMETA=META.."Shift+"`

**Comment by wilhelmy** [comment]
Should META+Button1 behave as "undock and move the resulting floating window around" on tiled windows? Currently it's used for resize, but META+Button2 can also be used to resize both float and tiled windows.

**Comment by rabarbar42** [comment]
Hi. I just used git to get the latest Notion snapshot, compiled it and ...I totally don't recognize it anymore. To begin with, how to switch back to old keybindings? Then, META+K doesn't work, numbered tabs don't work (either with meta or altmeta), and hide_tabs is broken...

...and there's no email list anymore
...and I could go on for a long time.

**Comment by raboof** [comment]
Thanks for bringing it up! (I see @knixeur also replied while I was typing this, so there might be some overlap ;) )

We're gearing up for a "Notion 4", and indeed we'd like to make some bigger changes.

Of course that should not be a "just put up with it" thing for existing users: while some of the defaults change, for most things it should ideally be possible to get the "old" behavior back with some configuration. For this we started on a migration guide which can be found at https://notionwm.net/migration.html (or, if you want to contribute to it, https://github.com/raboof/notion/blob/gh-pages/migration.md

> To begin with, how to switch back to old keybindings?

Embarassingly, it looks like we didn't document this in the migration guide just yet :(. It should be as simple as taking the `etc/cfg_notion3_keybindings.lua` and `etc/cfg_notion3_tiling.lua` from the Notion package and copying those to your `~/.notion/cfg_keybindings.lua` and `~/.notion/cfg_tiling.lua`.

> Then, META+K doesn't work

Indeed META+K is no longer used in the new keybindings, though it should be there when you change to the old ones.

I'd love it if you could try the new keybindings and give feedback! A keyboard reference can be brought up with `META+/`.

> numbered tabs don't work (either with meta or altmeta)

They look a bit different now (prefixing the title instead of being superimposed to them). 

> hide_tabs is broken...

Hmm, that doesn't ring a bell, could you open a separate issue for that?

> ...and there's no email list anymore

Actually the lists are still there at https://sourceforge.net/p/notion/mailman/ , but indeed they are no longer linked from the main page: they haven't seen much useful traffic for ages (even before we stopped linking to it, that's fairly recent), and I don't feel they add too much value on top of GitHub Issues and IRC.

> ...and I could go on for a long time.

Please do! This feedback is very useful (even if we may not always agree on all points ;) ).

**Comment by rabarbar42** [comment]
Hello, so let me start with kind of notice: I've been using ion3/notion since 2009 and don't intend to stop. I've been present in the "old" sourceforge lists using my real name, (Wojtek/Wojciech Aniszewski).   Okay, so that out of the way, I would also like to forcefully indicate that I understand very well the idea of GPL-izing notion, and that you guys have to rewrite some parts of the post-Tuomov-gon-crazy source, so hats off for that. 
Most importantly, what I would really love would be for Notion to become (L)GPL so that the Debian package (and Arch?) can exist again. Not that I have anything against using git, but I believe it would help broadening user base.  Looking at reddit and places, kids nowadays like i3 in Arch, and - oh, the horror - they think it is innovative. I consider it far inferior to Notion (the **scratchpad!**)

So, here's what I'll do. First of all, I will revert to pure git codebase (I have a ton of my own cfg_ files so I need to separate this). Besides, my Notion is heavily customized and themed (10 years mean something) so I must be careful to conserve that. I will try out the new keybindings as Arnout suggested. It is possible some functions (as splits) stopped working in the amalgamate-config I have now, I thing I mixed up my old files with the new ones. 

However, I'm skeptical here. For example, in a multi-tab window, a quick meta+k+number is a fundamental way to quickly jump to another subtab. If I had to press shift with that meta (which is Alt_L on my keyboard) It's an additional finger, which is the reason of my skepticism. In my own ("old") config, I have had no ALTMETA at all. 
I will investigate what happened with my hide_tabs, and open new issue if I can't fix it. I mostly saw: scratchpad window (urxvt in the scratchpad) has an unhidden tab, and the floats have un-hidden tabs as well. The tiled windows hide tabs properly.

I have wasted a hour or  two trying to connect to the IRC channel, it never worked either via the web interface (which seem to want me to register somewhere and gives no way to do that) and irssi (which, even with self-SSL signing, gives the " *** No Ident response" error and throws me out. So that's why I wrote here.

**Comment by raboof** [comment]
> I've been present in the "old" sourceforge lists using my real name, (Wojtek/Wojciech Aniszewski).

Ah, yes, I remember - good to see you here ;)

> what I would really love would be for Notion to become (L)GPL so that the Debian package (and Arch?) can exist again

Yes, agreed ;).

> However, I'm skeptical here.

I'm sure many existing users are - I'd be curious to hear your thoughts, perhaps there's additional things we can do to make it easier.

> in a multi-tab window, a quick meta+k+number is a fundamental way to quickly jump to another subtab. If I had to press shift with that meta (which is Alt_L on my keyboard) It's an additional finger, which is the reason of my skepticism. In my own ("old") config, I have had no ALTMETA at all

In the new keybindings, the recommended way to switch between the first 4 tabs is `META+A`, `META+S`, `META+D` and `META+F`. Certainly those are quick. Now beyond those 4 tabs it does get trickier - you can use `META+CapsLock` and the other window navigation features. In practice I find that when I have more than 4 tabs in a frame I'm making a mess anyway, and I should be closing/moving some tabs ;)

> scratchpad window (urxvt in the scratchpad) has an unhidden tab, and the floats have un-hidden tabs as well. The tiled windows hide tabs properly

I must admit I don't use hide_tabs myself, so it's entirely possible a bug slipped in there. Let's fix it :)

> I have wasted a hour or two trying to connect to the IRC channel

Ouch, that's painful, sorry to hear that. https://webchat.freenode.net/ *should* work (and we should link to it), but I use another client myself.

**Comment by raboof** [comment]
Added https://github.com/raboof/notion/pull/172 for the addition to the migration guide

**Comment by raboof** [comment]
> Make sure ALTMETA="" is interpreted as ALTMETA=META.."Shift+"

This is not actually possible, but with #154 at least we get a better error message in this case.

**Comment by raboof** [comment]
(closing this as the last task is tracked in its own issue)
