### ISSUE TITLE
BSDs don't support fchmod on sockets

### ISSUE THREAD

**Issue by madroach** [raboof/notion#16]
fchmod on sockets is a linuxsism. A similar effect can be reached on stream sockets by calling plain `chmod()` on the file path after `bind()`, but before `listen()`. See the patch below, which still uses `fchmod()`, but ignores the EINVAL error on BSDs.
Also remove `SOCK_MAX`, which is hardcoding a OS-specific limit. `sizeof()` does a better job here.

Christopher

```
From 98d3a98ffef86eab5a37234077983898a27e98f0 Mon Sep 17 00:00:00 2001
From: Christopher Zimmermann <madroach@gmerlin.de>
Date: Mon, 18 Apr 2016 13:10:53 +0200
Subject: [PATCH] fix unix domain socket on *BSD

---
 mod_notionflux/mod_notionflux.c        | 16 ++++++++++------
 mod_notionflux/notionflux.h            |  1 -
 mod_notionflux/notionflux/notionflux.c |  2 +-
 3 files changed, 11 insertions(+), 8 deletions(-)

diff --git mod_notionflux/mod_notionflux.c mod_notionflux/mod_notionflux.c
index c055c44..fab11e9 100644
--- mod_notionflux/mod_notionflux.c
+++ mod_notionflux/mod_notionflux.c
@@ -215,7 +215,7 @@ static bool start_listening()
         return FALSE;
     }

-    if(strlen(listenfile)>SOCK_MAX){
+    if(strlen(listenfile)>sizeof(addr.sun_path)){
         warn("Too long socket path");
         goto err;
     }
@@ -225,8 +225,9 @@ static bool start_listening()
         goto errwarn;

     if(fchmod(listenfd, S_IRUSR|S_IWUSR)<0)
-        goto errwarn;
-    
+        if(errno != EINVAL) /* fchmod() on socket is a linuxism. */
+       goto errwarn;
+
     addr.sun_family=AF_UNIX;
     strcpy(addr.sun_path, listenfile);

@@ -238,11 +239,14 @@ static bool start_listening()
             goto errwarn;
     }

-    if(bind(listenfd, (struct sockaddr*) &addr,
-            strlen(addr.sun_path)+sizeof(addr.sun_family))<0){
+    if(bind(listenfd, (struct sockaddr*) &addr, sizeof(addr))){
         goto errwarn;
     }
-    
+
+    /* chmod() after bind(), but before listen() is still early enough. */
+    if(chmod(listenfile, S_IRUSR|S_IWUSR)<0)
+   goto errwarn;
+
     if(listen(listenfd, MAX_SERVED)<0)
         goto errwarn;

diff --git mod_notionflux/notionflux.h mod_notionflux/notionflux.h
index 11cd783..f07c7aa 100644
--- mod_notionflux/notionflux.h
+++ mod_notionflux/notionflux.h
@@ -16,6 +16,5 @@
 #define MAX_SERVED 8
 #define CHUNK 1024
 #define MAX_DATA (1024*4)
-#define SOCK_MAX (108-1)

 #endif
diff --git mod_notionflux/notionflux/notionflux.c mod_notionflux/notionflux/notionflux.c
index 793882a..7fd0893 100644
--- mod_notionflux/notionflux/notionflux.c
+++ mod_notionflux/notionflux/notionflux.c
@@ -199,7 +199,7 @@ int main(int argc, char *argv[])
     if(sockname==NULL)
         die("No socket.");

-    if(strlen(sockname)>SOCK_MAX)
+    if(strlen(sockname)>sizeof(serv.sun_path))
         die("Socket name too long.");

     sock=socket(AF_UNIX, SOCK_STREAM, 0);
-- 
2.7.4
```

**Comment by wilhelmy** [comment]
Hello!

I happen to have made some changes in notionflux recently and now I am looking at this.

The way I remember it, on some BSD systems, socket permissions are still ignored entirely (or was it pipes or some other non-standard file?). We discussed this on IRC and @raboof dug out a stackoverflow post and apparently this was a bug in 4.3BSD (and derived OSes like HP-UX) but does not affect current BSD derivatives.

I'll integrate this later, at the moment I'm struggling with mkdtemp availability (would require `#define _POSIX_C_SOURCE 200809L` but currently the code base only uses `200108L`) and the tempfile-functions in general, because I would like to wrap it in a directory, since I don't want trust socket permissions to be reliable.

On Linux, `unix(7)` says that`       POSIX does not make
       any statement about the effect of the permissions on a socket file, and
       on some systems (e.g., older BSDs), the socket permissions are ignored.
       Portable programs should not rely on this feature for security.`

**Comment by wilhelmy** [comment]
I've written a patch for this, which uses mkdtemp and bumps `_POSIX_C_SOURCE` to `200809L` (but only for mod_notionflux). If this isn't ok, I can work around it by including a custom implementation of mkdtemp but I'd rather avoid it. Any opinions? Allegedly, mkdtemp was supported on most systems before 2008, but was only then added to POSIX, but I have no data.

**Comment by wilhelmy** [comment]
Also I'd like to note that since `fchmod` fails non-fatally with a warning on *BSD when it can't set the permissions, this is technically a local privilege escalation which allows any user with access to /tmp to run lua code inside your notion, if I read this correctly. Should we get a CVE assigned?

**Comment by raboof** [comment]
> I've written a patch for this, which uses mkdtemp and bumps _POSIX_C_SOURCE to 200809L (but only for mod_notionflux) (..) Any opinions?

That sounds fine to me!
