### ISSUE TITLE
Notion4: Mod4 + Shift + C kills ALL instances of a window, not the current client

### ISSUE THREAD

**Issue by pigmej** [raboof/notion#181]
1) Run few instances of firefox, google chrome, emacs
2) Focus one instance, `Mod4 + Shift + C`
3) All instances killed instead of current.

I've also observed issue with `urxvtc` where Notion4 seems to kill `urxvtd` too.

**Comment by pigmej** [comment]
So the keybindings that are defined are:

```bdoc("Kill client owning the client window.", "kill"),
    kpress(ALTMETA.."C", "WClientWin.kill(_)"),```

```bdoc("Query for context menu.", "qctx"),
kpress(ALTMETA.."C", "mod_query.query_menu(_, _sub, 'ctxmenu', 'Context menu:')"),```

```bdoc("Display context menu.", "ctx"),
kpress(META.."C", "mod_menu.menu(_, _sub, 'ctxmenu')"),```

```bdoc("Close current object.", "close"),
    kpress_wait(META.."C", "WRegion.rqclose_propagate(_, _sub)"),```

For some reason for me it's always `kill` or `ctxmenu`

**Comment by rabarbar42** [comment]
Cześć.
I'm not sure if I understand the problem. Do you mean you always get `WRegion.rqclose_propagate(_, _sub)")` instead of  `WClientWin.kill(_)`? 
I'm not using the original bindings, so the only kill command I have bound is
```
113        bdoc("Kill client owning the client window."),
114        kpress("C", "WClientWin.kill(_)"),
```
in cfg_bindings.lua. Never had an issue with "propagated" kill...
regards
Wojtek

**Comment by pigmej** [comment]
Cześć ;)

I’m always getting kill when i execute it on running window. So all my terminals are killed (I’m using urxvtd). Same with firefox. with altmeta+C

**Comment by wilhelmy** [comment]
I think this keybinding is defined twice, in multiple contexts?

Isn't ALTMETA bound to META.."+Shift"?

That is using the new keybindings, right?\

Either way, `WRegion.rqclose_propagate(_, _sub)")` is the right thing to call

**Comment by pigmej** [comment]
It. Is but these context don’t seem to be working. I always get only ctxmenu (no way to kill current window directly) and altmeta one propagates to kill parent of current window (no way to query for ctxmenu). I have default bindings for. Notion4 and notion4 master branch.

**Comment by raboof** [comment]
So the problem is there's several commands bound to `META+C`? Should we move 'Context menu' to `META+M` perhaps?

**Comment by pigmej** [comment]
I'm not sure how the different contexts should work in that case. But yes if these interfere then +1 for changing `Meta+C` to `Meta+M`.

I've submitted pull request #182

**Comment by r00t-** [comment]
this thread seems to be mostly about a confusion in terminology (besides overlapping mappings),
so i'd like to add:

killing a _client_ means disconnecting the _process_ from the X server, which, as a "side-effect", happens to close all it's windows.
closing a window is nicely asking the program to close it, which is why the function being referred to here is named `rqclose`.

it's quite typical and intuitive that kill is a shifted version of close, so mod+c = close and mod+shift+c = kill.
