### ISSUE TITLE
Clarification of titlebar click behavor when statusbar is at the bottom

### ISSUE THREAD

**Issue by c0dev0id** [raboof/notion#237]
Hello,

I recently switched from the original ion3 to notion. There is one difference I noticed in version 3-2017050501, which is still present in HEAD. So I'm not sure if it is a feature I don't understand or a real issue.

Prerequisite: The statusbar must be configured to be at the bottom.

Clicking above the frame title in ion3(!) focuses the frame. This would be what I expect.

In notion, it selects/hovers the client title like this:
![Ion3 Hover](https://codevoid.de/I/p/ion3_hover.png)
`scrot` does not record the mouse cursor, so I drew in where I clicked.

And here is a video demonstrating the behavior:
https://codevoid.de/9/p/2020-01-08_09-23-0cS6.mp4

Note, that I'm only clicking. I never held the mouse button down. When I move the mouse quick after clicking, I can even move the client to another frame.

Best Regards,
sdk

EDIT: It can be reproduced with the default config.

**Comment by wilhelmy** [comment]
Hm, interesting. "Works on my machine", but if I'm reading you right clicking on a window does the same as clicking+dragging that window instead of focusing it? Do you have focus follows mouse (seems so, I think we all do too)?
I think in order to solve this since I can't reproduce it (or can anyone else?) having an idea about the calls within notion would help.

Thanks for testing and reporting :)

**Comment by c0dev0id** [comment]
Hi Wilhelmy,

Thank  you for your reply. Yes, I have focus follows mouse enabled. But it's also reproducible when I delete my .notion directory and go with the defaults.

It's not exactly like dragging. The bar is not "attached" to the cursor. And the "moving" only works when I quickly move the cursor into another frame (within a second or so).

My "daily work-OS" is a Devuan (Debian without systemd) VMware VM running on Windows10.

I recorded another video.
https://codevoid4p3lowez.onion/9/p/2020-01-10_10-13-DaL4.mp4
(I forgot a word in the video... it should be "focus *works* too").

I also noticed, that the mouse cursor was moving smooth for me, while it is "hopping" in certain parts of the video. The "hopping" is in sync with what I described with "stuttering" in the video when I click+hold the first pixel row and drag it along the edge of the screen.

So maybe this is related to the VMware DRM driver.

How are you "debugging" notion? Starting it in xnest and attaching gdb? How about the lua part?
If you could give me a had with this, I might be able to dig to the problem myself.

**Comment by wilhelmy** [comment]
Sorry this took me so long. You can either attach to your normal notion (from a different tty, otherwise it can be annoying) and safely detach gdb again by quitting it or use Xephyr. Xnest might work too, but for Xephyr there's scripts in the repository (`./utils/xephyr/start-xephyr.sh &` and `./utils/xephyr/xephyr-notion-gdb.sh`). Notion (at least on git) is compiled with debug info (`cc -g`).

You could try setting a breakpoint on `ioncore_do_handle_buttonpress` and step through the code from there, look at arguments and local variables, isolate the error case and we can compare. If you start gdb within screen, you can copy the log out, or you could use something like asciinema to record the tty. How well do you know gdb?

Lua can generate backtraces, but I suspect the bug here is going to be in the C state.

**Comment by wilhelmy** [comment]
Seems like the function in question is `ioncore_handle_buttonpress`. In case I press and release, it immediately goes into the `ButtonRelease` case there. Does that by any chance not happen for you?

**Comment by c0dev0id** [comment]
@wilhelmy thanks for the pointers. I'll look into the areas you mentioned. It'll take some time as I can only test it at work (and usually there is... well... work to do). I'll update this issue asap.

**Comment by c0dev0id** [comment]
I'm not working in a VM anymore.
