### ISSUE TITLE
patch-releases are not tagged?

### ISSUE THREAD

**Issue by wilhelmy** [raboof/notion#307]
If I execute `version.sh` (or `notioncore.version()`), I see 4.0.0, not 4.0.2.
```
~/s/notion$ ./version.sh
4.0.0-24-gc4702bf4+20210102-0028
```
This is on the Lua 5.4 branch which is on to of master/HEAD. I think it should say 4.0.2?
Edit: might be an issue on my working copy, in which case please ignore.

**Comment by wilhelmy** [comment]
After pulling master, I get 4.0.1 but not 4.0.2... I really don't get this.

![wtf](https://user-images.githubusercontent.com/4211529/103455100-4d6d5080-4cea-11eb-88fa-87529c0d4ae7.png)

**Comment by raboof** [comment]
Ah, thanks for the heads-up. This is because for 4.0.1 I created an annotated tag, while for 4.0.2 I created a 'regular' tag from the GitHub UI.

We should decide and document which is better. If we prefer annotated tags that is enough, if we prefer 'regular' tags we should update the version.sh script to add the `--tags` parameter to `git describe`.

Annotated tags are slightly more secure: you can check the signature to see it was made by someone with physical access to my laptop. OTOH it's questionable if anyone would actually do that ;). Regular tags are move convenient as they can be created from the GitHub UI together with publishing the release notes, and slightly more safe since there's less chance that I accidentally tag the wrong commit.

Let's do annotated tags. I'll replace the 4.0.2 one.

**Comment by wilhelmy** [comment]
After `git pull -f --tags` the script reports the right version for me.
