### ISSUE TITLE
Layout is not being saved

### ISSUE THREAD

**Issue by edmcman** [raboof/notion#362]
Notion is not saving my layout for some reason, even if I manually use `session/save`.

Here are the contents of `.notion`:
```
~ $ find ~/.notion                                                                                                                                                                   09:58:03
/home/ed/.notion
/home/ed/.notion/.welcome_msg_displayed
/home/ed/.notion/gnome-session-this-is-deprecated
/home/ed/.notion/gnome-session-this-is-deprecated/saved_wd.lua
/home/ed/.notion/gnome-session-this-is-deprecated/saved_queryhist.lua
/home/ed/.notion/gnome-session-this-is-deprecated/cfg_statusd.lua
```

As the name suggests, I am running notion through a gnome session.  Does that have anything to do with the problem, or if is there anything else I should check?

**Comment by edmcman** [comment]
This is because I'm using GNOME under systemd, and it just ignores the messages:

https://gitlab.gnome.org/GNOME/mutter/-/issues/1183

**Comment by edmcman** [comment]
I tried to raise this on the gnome side.  [The gnome-session devs were jerks](https://gitlab.gnome.org/GNOME/gnome-session/-/issues/125).  I just opened an [issue](https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/98) with flashback, but I doubt they'll be able to do anything even if they want to, since the problem seems to be in gnome-session.

**Comment by wilhelmy** [comment]
Running notion as a WM in some context such as KDE or GNOME can yield unexpected results. I've only tried KDE plasma and notion misbehaves there too. I don't think anyone right now has the motivation or energy to maintain notion in some desktop environment session context - especially since the desktop environments are starting to make Wayland mandatory. Sorry about that.
