### ISSUE TITLE
Crashes with KDE

### ISSUE THREAD

**Issue by kbloom** [raboof/notion#63]
When I try to run Notion as my window manager under KDE Plasma (with the default configuration), notion crashes on startup.

I get the error message

    >> [702] X_GrabKey (33) 0x23e: BadAccess (attempt to access private resource denied)

but I don't know if this is related.

Backtrace attached

[gdb.txt](https://github.com/raboof/notion/files/2600306/gdb.txt)

**Comment by raboof** [comment]
Interesting, from the backtrace it seems to crash inside the `XQueryExtension` while getting the Query font with `XLoadQueryFont` in `defont_get_text_width`. Pretty surprising this is different between running under KDE Plasma compared to running under other DE's. Have you verified it works without KDE Plasma?

**Comment by raboof** [comment]
Did you build Notion from source or get some package? Which version/package exactly?

**Comment by kbloom** [comment]
I've been able to reproduce this with distribution packages

 * notion 3+2015061300-2+b1 in Debian
 * notion 3+2017050501-1 in Kubuntu cosmic.

The backtrace I attched to this bug comes the Debian package 3+2015061300-2+b1 rebuilt with debugging information enabled, and with stripping and optimization disabled (and with liblua5.2-0-dbg installed)

**Comment by raboof** [comment]
Interesting. I must admit I'm not familiar with KDE at all, so I'd appreciate some help. I'm also running Debian, and installed Plasma and kdm. How do I configure KDE/Plasma to use Notion as a window manager?

**Comment by kbloom** [comment]
So what I've been doing is running killall kwin_x11 from a terminal, and then starting notion from a terminal (typically one of my text terminals, so that I can debug without using my X desktop), however if you really want to replace the window manager by default (when it's not yet known to give you a working desktop), you need to set the `KDEWM` environment variable to the path of your window manager's binary. This is typically done by adding a shell script in `~/.config/plasma-workspace/env`.

**Comment by raboof** [comment]
Interesting! I can indeed reproduce your issue. Will do some digging
around. Thanks for the report!

**Comment by kbloom** [comment]
Note that once `notion` no longer crashes, you probably need a configuration of window hints that's similar to [this](https://www.reddit.com/r/unixporn/comments/64mihc/i3_kde_plasma_a_match_made_in_heaven/dka41y7/) i3 confguration in order to actually get something usable.

**Comment by raboof** [comment]
OK, so the backtrace is a bit of a red herring, because the error is returned by the X server asynchronously, so the trace doesn't point to the code that performs the 'bad' request, but to the code that observes the error.

It appears notion tries to grab some keys from the keybindings, but those have already been bound (presumably by some KDE component).

Instead of crashing, I think we should report on the bindings that failed to register. In the branch at https://github.com/raboof/notion/pull/new/warnOnBindFailures I changed the kill to a warning, but I haven't figured out a way to report which key couldn't be bound yet.

One obvious 'problem' is that now the Plasma 'Desktop' is displayed as a window. I guess we'd want to bind it to the root window of any non-tiled workspaces instead?

**Comment by kbloom** [comment]
That sounds like a good plan.

**Comment by raboof** [comment]
I updated the branch to only log the failures, could you have a look?

**Comment by kbloom** [comment]
That works. Now to figure out how to lay out KDE's stuff.
